require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegisteredUserForPublicationsController do

  # This should return the minimal set of attributes required to create a valid
  # RegisteredUserForPublication. As you add validations to RegisteredUserForPublication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "publication_unique_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegisteredUserForPublicationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all registered_user_for_publications as @registered_user_for_publications" do
      registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
      get :index, {}, valid_session
      assigns(:registered_user_for_publications).should eq([registered_user_for_publication])
    end
  end

  describe "GET show" do
    it "assigns the requested registered_user_for_publication as @registered_user_for_publication" do
      registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
      get :show, {:id => registered_user_for_publication.to_param}, valid_session
      assigns(:registered_user_for_publication).should eq(registered_user_for_publication)
    end
  end

  describe "GET new" do
    it "assigns a new registered_user_for_publication as @registered_user_for_publication" do
      get :new, {}, valid_session
      assigns(:registered_user_for_publication).should be_a_new(RegisteredUserForPublication)
    end
  end

  describe "GET edit" do
    it "assigns the requested registered_user_for_publication as @registered_user_for_publication" do
      registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
      get :edit, {:id => registered_user_for_publication.to_param}, valid_session
      assigns(:registered_user_for_publication).should eq(registered_user_for_publication)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RegisteredUserForPublication" do
        expect {
          post :create, {:registered_user_for_publication => valid_attributes}, valid_session
        }.to change(RegisteredUserForPublication, :count).by(1)
      end

      it "assigns a newly created registered_user_for_publication as @registered_user_for_publication" do
        post :create, {:registered_user_for_publication => valid_attributes}, valid_session
        assigns(:registered_user_for_publication).should be_a(RegisteredUserForPublication)
        assigns(:registered_user_for_publication).should be_persisted
      end

      it "redirects to the created registered_user_for_publication" do
        post :create, {:registered_user_for_publication => valid_attributes}, valid_session
        response.should redirect_to(RegisteredUserForPublication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved registered_user_for_publication as @registered_user_for_publication" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegisteredUserForPublication.any_instance.stub(:save).and_return(false)
        post :create, {:registered_user_for_publication => { "publication_unique_id" => "invalid value" }}, valid_session
        assigns(:registered_user_for_publication).should be_a_new(RegisteredUserForPublication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RegisteredUserForPublication.any_instance.stub(:save).and_return(false)
        post :create, {:registered_user_for_publication => { "publication_unique_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested registered_user_for_publication" do
        registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
        # Assuming there are no other registered_user_for_publications in the database, this
        # specifies that the RegisteredUserForPublication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RegisteredUserForPublication.any_instance.should_receive(:update).with({ "publication_unique_id" => "1" })
        put :update, {:id => registered_user_for_publication.to_param, :registered_user_for_publication => { "publication_unique_id" => "1" }}, valid_session
      end

      it "assigns the requested registered_user_for_publication as @registered_user_for_publication" do
        registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
        put :update, {:id => registered_user_for_publication.to_param, :registered_user_for_publication => valid_attributes}, valid_session
        assigns(:registered_user_for_publication).should eq(registered_user_for_publication)
      end

      it "redirects to the registered_user_for_publication" do
        registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
        put :update, {:id => registered_user_for_publication.to_param, :registered_user_for_publication => valid_attributes}, valid_session
        response.should redirect_to(registered_user_for_publication)
      end
    end

    describe "with invalid params" do
      it "assigns the registered_user_for_publication as @registered_user_for_publication" do
        registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegisteredUserForPublication.any_instance.stub(:save).and_return(false)
        put :update, {:id => registered_user_for_publication.to_param, :registered_user_for_publication => { "publication_unique_id" => "invalid value" }}, valid_session
        assigns(:registered_user_for_publication).should eq(registered_user_for_publication)
      end

      it "re-renders the 'edit' template" do
        registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RegisteredUserForPublication.any_instance.stub(:save).and_return(false)
        put :update, {:id => registered_user_for_publication.to_param, :registered_user_for_publication => { "publication_unique_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested registered_user_for_publication" do
      registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
      expect {
        delete :destroy, {:id => registered_user_for_publication.to_param}, valid_session
      }.to change(RegisteredUserForPublication, :count).by(-1)
    end

    it "redirects to the registered_user_for_publications list" do
      registered_user_for_publication = RegisteredUserForPublication.create! valid_attributes
      delete :destroy, {:id => registered_user_for_publication.to_param}, valid_session
      response.should redirect_to(registered_user_for_publications_url)
    end
  end

end
